workflows:
  ios_simulator_ci:
    name: iOS Personal Build (No App Store Connect)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TennisBallTracker.xcodeproj"
        XCODE_SCHEME: "TennisBallTracker"
        DERIVED_DATA_PATH: "$CM_BUILD_DIR/build"
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode Project
        script: xcodegen generate
      - name: Build Unsigned App
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination "generic/platform=iOS Simulator" \
            -configuration Debug \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $CM_BUILD_DIR/build/Build/Products/Debug-iphonesimulator/*.app
      - /tmp/xcodebuild_logs/*.log

  ios_sideload_ipa:
    name: iOS Sideload IPA (No App Store Connect)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "TennisBallTracker.xcodeproj"
        XCODE_SCHEME: "TennisBallTracker"
        DERIVED_DATA_PATH: "$CM_BUILD_DIR/build"
        IPA_NAME: "TennisBallTracker-unsigned.ipa"
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode Project
        script: xcodegen generate
      - name: Build Unsigned Device App
        script: |
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -configuration Release \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Package Unsigned IPA Artifact
        script: |
          APP_PATH="$DERIVED_DATA_PATH/Build/Products/Release-iphoneos/TennisBallTracker.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Expected app bundle not found at: $APP_PATH"
            exit 1
          fi
          PAYLOAD_DIR="$CM_BUILD_DIR/Payload"
          rm -rf "$PAYLOAD_DIR"
          mkdir -p "$PAYLOAD_DIR"
          cp -R "$APP_PATH" "$PAYLOAD_DIR/"
          cd "$CM_BUILD_DIR"
          zip -r "$IPA_NAME" Payload
          rm -rf Payload
    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - /tmp/xcodebuild_logs/*.log
